package com.example.algorithm.project.mapper;

import com.example.algorithm.entity.domain.GarbageSorting;
import java.util.List;

public interface GarbageSortingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table garbage_sorting
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table garbage_sorting
     *
     * @mbggenerated
     */
    int insert(GarbageSorting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table garbage_sorting
     *
     * @mbggenerated
     */
    GarbageSorting selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table garbage_sorting
     *
     * @mbggenerated
     */
    List<GarbageSorting> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table garbage_sorting
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GarbageSorting record);
}