package com.algorithm.project.mapper;

import com.algorithm.entity.domain.GarbageSorting;

import java.util.List;

public interface GarbageSortingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table garbagehandle
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table garbagehandle
     *
     * @mbggenerated
     */
    int insert(GarbageSorting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table garbagehandle
     *
     * @mbggenerated
     */
    GarbageSorting selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table garbagehandle
     *
     * @mbggenerated
     */
    List<GarbageSorting> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table garbagehandle
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GarbageSorting record);
}